# numpy sample

[reference](https://numpy.org/doc/stable/user/absolute_beginners.html)

## Install numpy

In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## import numpy

In [4]:
import numpy as np

## create your first numpy array

In [5]:
a = np.arange(6)

In [6]:
a.shape

(6,)

In [23]:
a.ndim

1

In [24]:
a.size

4

In [8]:
print(a[0:3])

[0 1 2]


In [46]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

## numpy functions for creation of arrays

In [10]:
np.zeros(2)

array([0., 0.])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.empty(3)

array([1.91002772e+227, 4.82675998e+233, 1.96086573e+243])

In [13]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [14]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.ones(2, dtype=np.int64)

array([1, 1], dtype=int64)

## Array manipulation

### sort array

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [18]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### combine array

In [19]:
a = np.array([1, 2, 3, 4])

In [20]:
b = np.array([5, 6])

In [22]:
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6])

### reshape array

In [25]:
a = np.arange(6)

In [26]:
a.shape

(6,)

In [27]:
b = a.reshape(2,3)

In [28]:
b.shape

(2, 3)

In [29]:
print(a)

[0 1 2 3 4 5]


In [30]:
print(b)

[[0 1 2]
 [3 4 5]]


In [31]:
a.ndim

1

In [32]:
b.ndim

2

### adding new axis

In [33]:
a = np.array([1, 2, 3, 4, 5, 6])

In [34]:
a2 = a[np.newaxis, :]

In [35]:
a2.shape

(1, 6)

In [36]:
print(a2)

[[1 2 3 4 5 6]]


In [37]:
a3 = a[:, np.newaxis]

In [38]:
a3.shape

(6, 1)

In [39]:
print(a3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### indexing / slicing

In [40]:
a = np.array([1, 2, 3, 4, 5, 6])

In [41]:
a[a > 2]

array([3, 4, 5, 6])

In [42]:
a[2:4]

array([3, 4])

In [43]:
a >= 5

array([False, False, False, False,  True,  True])

### basic operations

In [49]:
a = np.random.rand(6)

In [50]:
print(a)

[0.8109548  0.77889328 0.58416948 0.14387918 0.63893969 0.95611095]


In [68]:
np.flip(a)

array([0.95611095, 0.63893969, 0.14387918, 0.58416948, 0.77889328,
       0.8109548 ])

In [51]:
a * 1.1

array([0.89205028, 0.85678261, 0.64258643, 0.15826709, 0.70283366,
       1.05172204])

In [52]:
a + np.ones(6)

array([1.8109548 , 1.77889328, 1.58416948, 1.14387918, 1.63893969,
       1.95611095])

In [53]:
a.sum()

3.912947376817277

In [54]:
a.min()

0.14387917638123704

In [55]:
a.max()

0.9561109496671696

In [56]:
b = np.array([[1, 1], [2, 2]])

In [67]:
b.transpose()

array([[1, 2],
       [1, 2]])

In [57]:
b.sum()

6

In [58]:
b.sum(axis=1)

array([2, 4])

In [59]:
b.sum(axis=0)

array([3, 3])

In [64]:
np.ones((2,3)) * np.random.rand(2,3)

array([[0.08091099, 0.5819709 , 0.82158256],
       [0.32930923, 0.49853607, 0.8318008 ]])

In [66]:
np.unique(np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20]))

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Saving and loading

In [72]:
a = np.arange(6)

In [73]:
print(a)

[0 1 2 3 4 5]


In [76]:
np.save("a.npy",a)

In [77]:
b = np.load("a.npy")

In [78]:
print(b)

[0 1 2 3 4 5]
